version: "3.8"
services:
  # Django app
  backend_cart:
    container_name: lilthi_ms_cart
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    # networks:
    #   - lilthi_net  # Agregamos el enlace de red personalizado
    depends_on:
      - db_cart
      - redis_cart
    # command: ["./wait-for-it.sh", "db_cart:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
  # Event Queue Kafka
  car_queue:
    build: .
    command: >
      sh -c "python consumer.py"
    depends_on:
      - db_cart
  # PostgreSQL
  db_cart:
    container_name: django_db_cart_postgres
    # hostname: db_cart
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=lilthi
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lilthi_cart_db
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    # networks:
    #   - lilthi_net  # Agregamos el enlace de red personalizado

  # Redis
  redis_cart:
    container_name: django_cart_redis
    image: redis:latest
    ports:
      - "6380:6379"
    # networks:
    #   - lilthi_net  # Agregamos el enlace de red personalizado

# Agregamos la definición de la red personalizada
# networks:
#   lilthi_net:
#     driver: bridge
