version: "3.8"
services:
  # Django app
  backend_auth:
    container_name: lilthi_ms_auth
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # networks:
    #   - lilthi_net  # Agregamos el enlace de red personalizado
    depends_on:
      - db_auth
      - redis_auth
    # command: ["./wait-for-it.sh", "db_auth:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]

  # PostgreSQL
  db_auth:
    container_name: django_db_auth_postgres
    # hostname: db_auth
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=lilthi
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lilthi_auth_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    # networks:
    #   - lilthi_net  # Agregamos el enlace de red personalizado

  # Redis
  redis_auth:
    container_name: django_auth_redis
    image: redis:latest
    ports:
      - "6379:6379"
    # networks:
    #   - lilthi_net  # Agregamos el enlace de red personalizado

# Agregamos la definición de la red personalizada
# networks:
#   lilthi_net:
#     driver: bridge
